### PR TITLE
fixed US35 & 36

### PR DESCRIPTION
**Pull request by vporta**
Made corrections. Prints correct output. Tested against the testing.ged file. Lines 23 and 112 of testing.ged were edited to test the output.

### CODE REVIEW

**Review by conniejmiller — CHANGES_REQUESTED** [review]
You can't change the existing records in testing.ged.  They are satisfying other tests.  You need to add new data for these tests.

The format of the date you are printing differs from all other dates we display.  Please display a common format.

Most importantly, only the first recent birth or death is listed, not all in the file.  You need to make better test data for both you testing and the project output.

**Review by conniejmiller — CHANGES_REQUESTED** [review]
test data is ok....but the code still wont' work if there are multiples.  Try adding a recent birth and death for each of the new individuals you added.  You'll see that only one of them prints.

**Comment by vporta** [comment]
Prints multiples now.

**Comment by conniejmiller** [comment]
looks good except the misspelled month on Mary Smith's birthday was necessary for test US42.

**Review by conniejmiller — APPROVED** [review]

**Pull request merged**
