### PR TITLE
User stories 35 & 36

### PR DESCRIPTION
**Pull request by vporta**

### CODE REVIEW

**Review by conniejmiller — CHANGES_REQUESTED** [review]
minor comments:
1) in the comment of both functions, the -1 is returned if the date is BEFORE the last 30 days, AFTER the last 30 days and WITHIN the last 30 days are the same thing.
2) you should add a test where someone was born or died more than 30 days ago.  The 2 tests you have here do not cover all the possibilities.
3) You need to add data to our test data so we can show output that represents all stories in our output.
4) we seem to have different code standards,  mine keeps complaining if we have  more or less than 2 lines between functions.  I don't know what the standard should be.

**Comment by vporta** [comment]
Fixed comments. 
Added extra test cases (all pass). 
Fiddled with the test data. I believe I'm getting correct output. 
Two spaces for functions, not methods, is the PEP8 standard that we agreed to. Methods should get one space.

**Comment by conniejmiller** [comment]
I don't see any new changes.....could be my lack of gitHub knowledge.

**Review by ryancoppa — APPROVED** [review]
Looks good.

**Comment by ryancoppa** [comment]
Regarding the code standard, my editor is using `pep8` and `pylint.` It should recommend two lines between free functions and one line between functions in a class, I believe.

**Comment by vporta** [comment]
Okay. If good then someone merge it so we can get Ryan's branch merged. @ryancoppa @conniejmiller

**Comment by conniejmiller** [comment]
How can I see the changes after my comments?  I don't see updated comments, new test cases, or changes to the test data file.

**Comment by vporta** [comment]
Try checking now @conniejmiller

**Comment by conniejmiller** [comment]
code looks good....but new data file has an extra HEAD and TRLR in the middle of the file...and an extra line at the end.

**Comment by vporta** [comment]
Ready to merge when you are.

**Pull request merged**
