### PR TITLE
VPorta Sprint 2 

### PR DESCRIPTION
**Pull request by vporta**

### CODE REVIEW

**Comment by ryancoppa** [comment]
Looks good to me

**Comment by conniejmiller** [comment]
US30: Non-living, non-married, or divorced person - this is not a requirement.  Is there a need to display this?
US31: List of living single people over 30 - do you have test data for this?  Nothing is printing.

**Comment by conniejmiller** [comment]
US 30 - lists on separate lines; US31 - lists on single line.

We should be consistent.

**Comment by vporta** [comment]
It prints on the same line for me.

**Comment by vporta** [comment]
I removed the print you specified. Here is my output:
US30: Living married person: Constance Joan /Lewis/
US30: Living married person: John Anderson /Miller/
US31: List of living single people over 30: p5, Jeffrey Clement /Lewis/
US31: List of living single people over 30: p8, Frank /Miller/ Jr
US31: List of living single people over 30: p14, Bryan Ferris /Miller/
US31: List of living single people over 30: p15, Theresa Ann /Holmes/

**Pull request merged**
