### PR TITLE
refactored valid_months and valid_lifetime functions and test cases

### PR DESCRIPTION
**Pull request by vporta**
I refactored valid_month and valid_lifetime. I extracted two functions from valid_lifetime(birth, death): is_below150_years(life_years) and calculate_lifeyears(death_date, birth_date); and I extracted one function from valid_month: is_in_month(month, months). 
Also, I added one test case: test_is_below150_years. 

Automated test cases pass.

### CODE REVIEW

**Review by conniejmiller — CHANGES_REQUESTED** [review]
I don't think the is_in_month and is_below150_years functions add any value.  They meet the needs of the homework but I don't think we should merge this with our group assignment.

**Comment by vporta** [comment]
Okay, Connie. It does make it easier to test. Ryan, what do you think?

**Review by ryancoppa — COMMENTED** [review]
I tend to agree with Connie, while this would meet the homework assignment, I'm not sure it improves the overall function of the code. Maybe a more general function that does multiple things (to reduce the overall number of functions) would be helpful. But here I think we are keeping the same or increasing the total function count.

**Comment by vporta** [comment]
Yea it doesn't make much of a difference to the codebase overall, though it's good practice to keep functions small (15 lines or less). I don't feel we should have a general function that does multiple things. There are a few functions that are way too large that we should break into smaller functions or create classes. I'll close the PR now since I've been outvoted.

**Comment by ryancoppa** [comment]
I agree with not having a general function doing lots of things, can we re-use any of this code after we merged my branch? I think it would be good to reduce the overall size of some of our functions.

**Comment by vporta** [comment]
I can try to use some of it.

**Pull request closed without merging**
