### PR TITLE
Sort siblings by age

### PR DESCRIPTION
**Pull request by ryancoppa**
Include refactor of `get_age` and `valid_month`

### CODE REVIEW

**Review by conniejmiller — CHANGES_REQUESTED** [review]
this throws an error when executed on our TEST file.  The record with an invalid month causes the problem.  I think you need to call valid_month() from within this routine so we can run it to get valid output for all stories.

**Comment by ryancoppa** [comment]
I was able to run test.py without exception, can you post the output?

**Comment by ryancoppa** [comment]
Fixed. If we include `valid_month` we have a circular dependency, so I just caught exceptions.

**Review by conniejmiller — APPROVED** [review]
good now....need the same change before you merge US34

**Pull request merged**
