### PR TITLE
US 25 and 41

### PR DESCRIPTION
**Pull request by vporta**
US 25 has sample output in the output txt file. 
Have a look at US 41, process_partial_dates(date). I didn't want to integrate it with other functions because it would break everything. Let me know how you'd like to approach this.

### CODE REVIEW

**Review by conniejmiller — CHANGES_REQUESTED** [review]
US25 - works great but can the output be more consistent with others, something like: Anomaly US25: Family @F7@ contains duplicate child name and birthday: [('Jane', '9 FEB 2010')]  

US41  - Seems to work but we do need to incorporate it. 
Can you call this function for all dates in the two lists...maybe from project.py before line 90 so that the "family" and "individual" lists will contain good dates?  If you display the US41 message there, it should be good enough and then all other tests will run on good data.

We need a project_output that reflects both tests as well as all others.

**Review by ryancoppa — APPROVED** [review]
Agree with Connie, looks good. Once the output is updated it should be good to merge.

**Comment by vporta** [comment]
US41 is incorporated.

**Review by conniejmiller — APPROVED** [review]
US 41 looks good.  
Can you update the output on US25?

**Comment by vporta** [comment]
I'll have to do a major rewrite of both functions and change the data structure in order to include that one tag. Since it works, we should merge this PR and Ryan's and I can fiddle with it in another branch this weekend.

**Pull request merged**
